[package]
authors = ["Joshua Ji <joshuanianji@users.noreply.github.com>"]
edition = "2018"
name = "ahmad_bot"
version = "0.1.0"

[dependencies]
dotenv = "0.15"
tracing = "0.1.23"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

[dependencies.songbird]
version = "0.1.6"

[dependencies.serenity]
features = ["cache", "framework", "standard_framework", "voice", "http", "rustls_backend"]
version = "0.10"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "signal"]
version = "1.0"
