version: "3.9"
services:
  bot:
    tty: true
    environment:
      - TERM=xterm-256color
      - CONFIG_PATH=/run/secrets/bot_config
      - SERVER_HOST=http://server:3001 
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    secrets:
      - bot_config
    links: 
      - "server"

  server:
    tty: true
    environment:
      - TERM=xterm-256color
      - CONFIG_PATH=/run/secrets/server_config
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    secrets:
      - server_config
