name: "Update Docker Image in Production"
description: "Updates the Docker Image in my Digital Ocean Server"
inputs:
  service:
    required: true
    description: "The name of the service to update"
  # Remember that Composite actions cannot read secrets.
  ssh_host:
    required: true
    description: "The host IP of the Digital Ocean server"
  ssh_key:
    required: true
    description: "The SSH key to use for authentication"

# https://phoenixnap.com/kb/update-docker-image-container
runs:
  using: "composite"
  steps:
    - name: Download and extract the latest Docker Image on Server
      uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
      with:
        host: ${{ inputs.ssh_host }}
        username: joshua
        key: ${{ inputs.ssh_key }}
        port: 22
        script: |
          docker container ls | grep treehouse
          docker image ls | grep treehouse
