name: "Build and Deploy Docker Image"
description: "Build and deploy a Docker image to GitHub Container Registry"
inputs:
  service:
    required: true
    description: "The name of the service to build and deploy"
  repo_token:
    required: true
    description: "The GitHub token to use for authentication"

runs:
  using: "composite"
  steps:
    - name: Build and Publish
      run: ./.github/actions/publish-docker-image/run.sh ${{ inputs.service }} ${{ inputs.repo_token }}
      shell: bash
