name: "Build and Deploy Docker Image"
description: "Build and deploy a Docker image to GitHub Container Registry"
inputs:
  service:
    required: true
    description: "The name of the service to build and deploy"
  repo_token:
    required: true
    description: "The GitHub token to use for authentication"

runs:
  using: "composite"
  steps:
    - name: Login to Github Container Registry
      uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo_token }}

    - name: Build the Docker Image
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.dev.yml build ${{ inputs.service }}
      shell: bash

    - name: Push Docker Image with SHA Tag
      run: |
        docker tag ${{ inputs.service }} ghcr.io/$TAG_SHA
        docker push ghcr.io/$TAG_SHA
      shell: bash
      env:
        TAG_SHA: ${{ github.repository }}.${{ inputs.service }}:${{ github.sha }}

    - name: Push Docker Image with :latest tag
      run: |
        docker tag ${{ inputs.service }} ghcr.io/$TAG_SHA
        docker push ghcr.io/$TAG_SHA
      shell: bash
      env:
        TAG_SHA: ${{ github.repository }}.${{ inputs.service }}:latest
