name: Create & Upload Server Image to GHCR

on:
  push:
    branches: [main]
    paths:
      # only push to changes in apps/bot or other necessary images
      - "apps/server/**"
      - "server.Dockerfile"
      - "docker-compose*.yml" # docker compose files
      - ".github/workflows/deploy-server.yml" # this file
      - ".github/actions/publish-docker-image/**" # Dependencies
      - "!*.md" # ignore markdown files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout repo
        uses: actions/checkout@v2

      # Is this necessary?
      - name: ✏️ Write bot-config.yml
        run: echo "{{ secrets.SERVER_CONFIG_YML }}" > server-config.yml

      - name: Build and deploy Bot
        # Directory name only
        uses: ./.github/actions/publish-docker-image
        with:
          service: "server"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  update-server-image:
    name: Update Docker Image in Production
    runs-on: ubuntu-latest
    steps:
      # Skopeo (https://github.com/containers/skopeo)
      # Allows us to work with remote image registries
      - name: Install Skopeo
        run: sudo apt-get -y install skopeo

      - name: Info about Image
        run: |
          echo "Image name: Bot"
          skopeo inspect docker://ghcr.io/joshuanianji/treehouse-bot.server:latest | jq '.Name,.Created,.Digest'

      - name: Update Docker Image in Prod
        uses: ./.github/actions/update-docker-image-prod
        with:
          service: "server"
          ssh_host: "{{ secrets.SSH_HOST }}"
          ssh_key: "{{ secrets.SSH_KEY }}"
