name: Create & Upload Discord Bot Docker Image to GHCR

on:
  push:
    branches: [main]
    paths:
      # only push to changes in apps/bot or other necessary images
      - "apps/bot/**"
      - "bot.Dockerfile"
      - ".github/workflows/deploy-bot.yml" # this file
      - ".github/actions/publish-docker-image/**" # Dependencies
      - "!*.md" # ignore markdown files

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout repo
        uses: actions/checkout@v2

      # Is this necessary?
      - name: ✏️ Write bot-config.yml
        run: echo "{{ secrets.BOT_CONFIG_YML }}" > bot-config.yml

      - name: Build and deploy Bot
        # Directory name only
        uses: ./.github/actions/publish-docker-image
        with:
          service: "bot"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
