name: Create & Upload Docker Image to GHCR

on:
  push:
    branches: [main]
    paths:
      # only push to changes in apps/bot, apps/server, or the dockerfiles
      - "apps/bot/**"
      - "apps/server/**"
      - "*.Dockerfile"
      - "docker-compose.yml"
      - "package.json"
      - ".dockerignore"
      - "!*.md"
      - ".github/workflows/docker-images.yml" # this file

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏁 Checkout repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔖 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 🐋 Build and push Docker image
        uses: pennsignals/publish_docker-compose@6863aa71ab6883d7223990efb38035330aeea7f5
        with:
          docker_compose: "docker-compose.yml"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
