name: Push required code to Prod Branch

on:
  push:
    branches: [main]
    paths:
      # only push to changes in docker-compose
      - "docker-compose.yml"
      - "docker-compose.prod.yml"
      - ".github/workflows/push-to-prod.yml" # this file

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout repo
        uses: actions/checkout@v2

      - name: 🚚 Move files to RSync with Server to /out
        run: |
          mkdir out
          mv docker-compose.yml docker-compose.prod.yml out/

      - name: 🔧 Add Config files to /out
        run: |
          echo "{{ secrets.BOT_CONFIG_YML }}" > bot-config.yml
          echo "{{ secrets.SERVER_CONFIG_YML }}" > server-config.yml

      - name: 🚀 Deploy with rsync
        run: rsync -avz ./out/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/projects/treehouse-bot/
